### ISSUE TITLE
执行到第6步总是绑定失败

### ISSUE THREAD

**Issue by cnliucheng** [rainerosion/E5SubBot#1]
![image](https://user-images.githubusercontent.com/32115849/224115228-7bf7e462-d413-4833-b923-bdb33ff1d3b9.jpeg)

**Comment by rainerosion** [comment]
由于原项目已支持sqlite，该项目已不再维护，请使用原项目。[https://github.com/iyear/E5SubBot](https://github.com/iyear/E5SubBot)
